- role: Invited Reviewers
  items:
    - "2023: IEEE BigData 2023."
    - "2024: AAAI 2024, NeurIPS 2024."
    - "2025: AAAI 2025, AISTATS 2025, ICLR 2025, ICML 2025, NeurIPS 2025."
    - "2026: AAAI 2026, AISTATS 2026, ICLR 2026, ICML 2026."

# - role: Teaching Assistant
#   items:
#     - "UIUC, CS412 XXX, 202X Spring."